version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - YOUR_ENV_VARIABLES_HERE
    networks:
      - app-network
    init: true

networks:
  app-network:
    driver: bridge
